# Generated by Django 3.2.4 on 2021-07-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'WHITE'), ('black', 'BLACK'), ('blue', 'BLUE'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('red', 'RED'), ('tomato', 'TOMATO'), ('pink', 'PINK'), ('teal', 'TEAL'), ('brown', 'BROWN')], max_length=50, verbose_name='Rang nommi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Rasmi')),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('old_price', models.PositiveIntegerField(default=0, verbose_name='Avvalgi Narxi')),
                ('description', models.TextField(verbose_name='Tovar haqida')),
                ('instock', models.BooleanField(default=True, verbose_name='Bor / Yok')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('other_colors', models.ManyToManyField(to='shop.Colors')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Tovar alohida rasmlari')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Tovar rasmlari',
                'verbose_name_plural': 'Tovar rasmlari',
            },
        ),
    ]
