# Generated by Django 3.2.4 on 2021-08-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210709_1434'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism-Sharifi')),
                ('state', models.CharField(choices=[('fergana', "Farg'ona"), ('namangan', 'Namangan'), ('andijan', 'Andijon')], max_length=50, verbose_name='Viloyat')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('total_sum', models.PositiveIntegerField(default=0, verbose_name='Umumiy narx')),
                ('payed', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='cart.OrderProduct')),
            ],
        ),
    ]
